### ISSUE TITLE
[enhancement] Adding auto-door opening sequence or their destruction.

### ISSUE THREAD

**Issue by iojforever** [Raul125/SCPLockdown#5]
**AutoDoor opening and/or their destruction:**

> My idea comes from the previously added function of auto-opening doors at the end of the timer. I think the ability to configure SCP Objects door break and Class-D chamber doors open would be a nice innovation. Also will suit with lights plugin that has an initial lights-off configuration.

**Is this really necessary?**

> It is not necessary. It's just that it would combine well, not only as a way to slow down the start of the game, but also to explain it from the lore side of the facility. Door is not working correctly, after all.

**Comment by Raul125** [comment]
#9
