### ISSUE TITLE
SCP-939 escapes immediately after the start of the round

### ISSUE THREAD

**Issue by Expand8991** [Raul125/SCPLockdown#8]
The doors of the SCP 939 are unlocked from the beginning of the round, despite the fact that according to the config 939 should run only after about three minutes. Here is the config:

scp_lockdown:
  is_enabled: true
  # The affected SCPs and their duration [seconds] of lockdown.
  affected_scps:
    Scp079: 120
    Scp173: 165
    Scp096: 120
    Scp106: 120
    Scp049: 120
    Scp93989: 120
    Scp93953: 120
  # Can the Scp-079 use/switch cameras while is in lockdown?
  scp079_camera: true
  # Use this if you want to lock any doors, if you enabled a lockdown of an scp in AffectedScps cfg you don't need to enable their doors lockdown here, Use PrisonDoor to lock class-d cells.
  affected_doors:
    CheckpointLczA: 30
    CheckpointLczB: 30
    CheckpointEntrance: 30
    PrisonDoor: 165
    GR18: 165
    Scp914: 165
    Scp012: 165
    Scp012Locker: 165
    Scp173Armory: 165
    LczArmory: 165
    HczArmory: 165
    NukeArmory: 165
    HID: 165
  # Use this if you want send cassies with a specified timing.
  cassies:
  - bell_start pitch_1.075 . attention all personnel . work day has been started . . cassiesystem activated . . Starting scan all system pitch_2.0 .g3 .g3 .g5 .g2 .g1 .g4  pitch_1.075 . Stable . Scan all Subsystem pitch_2.0 .g3 .g3 .g5 .g2 .g1 .g4 pitch_1.075 . Stable . . Activated Defense system in Surface Zone pitch_0.5 .g5 pitch_1.075 Good Work Day . . Secure . Contain . Protect bell_end:5
  - pitch_0.2 jam_001_2 .g2 pitch_0.6 .g1 pitch_0.3 .g3 pitch_0.97 . warning . doors and lights systems .g1 .g4 malfunction .g3 detected .g2 .g1 . . . . . . . pitch_0.2 .g4 pitch_0.6 .g1 pitch_0.95 . emergency alert . pitch_0.7 .g3 pitch_0.93 . scpsubjects containment breach detected pitch_0.2 .g1 pitch_0.90 AllRemaining jam_001_2 .g2 pitch_0.85 UncalculatedSCPsLeft pitch_0.2 .g3 . .g3 . pitch_0.5 .g5 . pitch_0.96 jam_001_3 lights pitch_0.97 system pitch_0.99 resumed pitch_1 operational:120
  - bell_start Attention all personnel . . The Alpha Warhead Emergency Detonation Sequence will be started in . TMinus . 10 Minutes bell_end:1800
  - bell_start Danger . . The Alpha Warhead Emergency Detonation Sequence will be started in . TMinus . 5 Minutes bell_end:2100
  - bell_start Danger . . The Alpha Warhead Emergency Detonation Sequence will be started in . TMinus . 1 Minute bell_end:2340
  # If enabled, the scps will see a hint, else they will see a broadcast.
  use_hints: true
  # Displayed to the scps when his lockdown is finished.
  scps_text:
    Scp079: <color=red>Containment Breach!</color>
    Scp173: <color=red>Containment Breach!</color>
    Scp096: <color=red>Containment Breach!</color>
    Scp106: <color=red>Containment Breach!</color>
    Scp049: <color=red>Containment Breach!</color>
    Scp93989: <color=red>Containment Breach!</color>
    Scp93953: <color=red>Containment Breach!</color>

**Comment by Raul125** [comment]
Try the 2.1.0 version.
